http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    frontend-http:
      rule: "Host(`vote.saltybots.com`) && PathPrefix(`/`)"
      service: frontend
      entryPoints:
        - web
      middlewares:
        - redirect-to-https

    backend-http:
      rule: "Host(`vote.saltybots.com`) && PathPrefix(`/api`)"
      service: backend
      entryPoints:
        - web
      middlewares:
        - redirect-to-https

    grafana-http:
      rule: "Host(`monitoring.vote.saltybots.com`) && PathPrefix(`/`)"
      service: grafana
      entryPoints:
        - web
      middlewares:
        - redirect-to-https

    # HTTPS routers
    frontend:
      rule: "Host(`vote.saltybots.com`) && PathPrefix(`/`)"
      service: frontend
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    backend:
      rule: "Host(`vote.saltybots.com`) && PathPrefix(`/api`)"
      service: backend
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    grafana:
      rule: "Host(`monitoring.vote.saltybots.com`) && PathPrefix(`/`)"
      service: grafana
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://sv-frontend:5173"

    backend:
      loadBalancer:
        servers:
          - url: "http://sv-backend:8080"

    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
